shoulder1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder1_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

shoulder2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder2_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

knee_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: knee_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}