leg_robot_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder1_joint
    - shoulder2_joint
    - knee_joint
  gains:
    shoulder1_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    shoulder2_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    knee_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
